name: Next.js CI

on:
  workflow_call:

jobs:
  playwright:
    uses: PeterLaudel/actions/.github/workflows/playwright.yml@main
  nodetest:
    uses: PeterLaudel/actions/.github/workflows/nodetest.yml@main