name: Test node application

on:
  workflow_call:

jobs:
  create-image-tag:
    name: Create image tag
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.create.outputs.TAG }}
    steps:
      - name: Extract image tag
        id: create
        run: |
          IMAGE_TAG="$BRANCH_NAME-${{ github.run_number }}-$(echo $GITHUB_SHA | cut -c1-7)"
          echo "TAG=${IMAGE_TAG}" >> "$GITHUB_OUTPUT"
          echo "Final IMAGE_TAG: ${IMAGE_TAG}"
    env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

  build-image:
    needs: create-image-tag
    name: Build Docker image
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ needs.create-image-tag.outputs.image-tag }}

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          access_token_lifetime: 300s

      # Login to Google Artifact Registry
      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west10-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 🏗️ Build the 'builder' stage
      - name: Build builder stage
        uses: docker/build-push-action@v6
        with:
          push: false
          load: false
          target: builder
          tags: builder:${{ env.IMAGE_TAG }}
          outputs: type=docker,dest=${{ runner.temp }}/${{ env.IMAGE_TAG }}.tar
          cache-from: type=registry,ref=europe-west10-docker.pkg.dev/psychotherapie-seliger-adm/images/psychotherapie-seliger:buildcache
          cache-to: type=registry,ref=europe-west10-docker.pkg.dev/psychotherapie-seliger-adm/images/psychotherapie-seliger:buildcache,mode=max

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_TAG }}
          path: ${{ runner.temp }}/${{ env.IMAGE_TAG }}.tar

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs:
      - build-image
      - create-image-tag
    env:
      IMAGE_TAG: ${{ needs.create-image-tag.outputs.image-tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            docker-compose.yml

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_TAG }}
          path: ${{ runner.temp }}

      - name: Load builder image
        run: |
          docker load -i ${{ runner.temp }}/${{ env.IMAGE_TAG }}.tar

      - name: Run tests
        run: IMAGE=builder:${{ env.IMAGE_TAG }} docker compose up --abort-on-container-exit --exit-code-from app

  lint:
    name: Run lint
    runs-on: ubuntu-latest
    needs:
      - build-image
      - create-image-tag
    env:
      IMAGE_TAG: ${{ needs.create-image-tag.outputs.image-tag }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_TAG }}
          path: ${{ runner.temp }}

      - name: Load builder image
        run: |
          docker load -i ${{ runner.temp }}/${{ env.IMAGE_TAG }}.tar

      - name: Run lint
        run: docker run --rm builder:${{ env.IMAGE_TAG }} npm run lint

  typecheck:
    name: Run typecheck
    runs-on: ubuntu-latest
    needs:
      - build-image
      - create-image-tag
    env:
      IMAGE_TAG: ${{ needs.create-image-tag.outputs.image-tag }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_TAG }}
          path: ${{ runner.temp }}

      - name: Load builder image
        run: |
          docker load -i ${{ runner.temp }}/${{ env.IMAGE_TAG }}.tar

      - name: Run typecheck
        run: docker run --rm builder:${{ env.IMAGE_TAG }} npm run typecheck